### ISSUE TITLE
Backdoor detected by Windows Defender

### ISSUE THREAD

**Issue by nongshaba1337** [PhHitachi/HackBar#2]
guys, this hackbar has backdoor, beware

**Comment by PhHitachi** [comment]
then prove it to us

**Comment by nongshaba1337** [comment]
> then prove it to us

Check yourself installing on windows 10 , please don't fool people using your retarded tool.

**Comment by PhHitachi** [comment]
of cource, this xul extenstion and not html

>please don't fool people using your retarded tool. 

im not forcing you to download it and use it lol ;P

**Comment by PhHitachi** [comment]
https://www.zdnet.com/article/mozilla-announces-ban-on-firefox-extensions-containing-obfuscated-code

read skids

**Comment by PhHitachi** [comment]
find the virus on open-source https://github.com/PhHitachi/HackBar/tree/master/src then if you have found tell me or post on social media and tag  your skids friends
